version: '3.9'

x-env: &env
  MODEL_NAME: qwen3:8b
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  POSTGRES_DB: ollama_db

x-restart-policy: &restart
  on-failure

services:
  llama:
    image: docker.io/ollama/ollama:0.8.0
    container_name: ollama
    ports:
      - 11434:11434
    restart: *restart
    environment:
      <<: *env
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    volumes:
      - ./run_ollama.sh:/run_ollama.sh
    entrypoint: "sh"
    command: "/run_ollama.sh"

  postgres:
    image: docker.io/postgres:17.5
    container_name: postgres
    ports:
      - 5432:5432
    restart: *restart
    environment:
      <<: *env
